# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and rsync

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
    - uses: actions/checkout@release
    - name: Use Node.js ${{ matrix.node-version }} build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmmirror.com'
        cache: 'npm'
    - run: npm install --force
    - run: npm run build
    
  rsync:
    runs-on: ubuntu-18.04
    steps:
    - name: Use rsync
    - run: ls
